/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChainPropertiesDTO } from './ChainPropertiesDTO';
import { NetworkPropertiesDTO } from "./NetworkPropertiesDTO";
import { PluginsPropertiesDTO } from "./PluginsPropertiesDTO";
/**
 *
 * @export
 * @interface NetworkConfigurationDTO
 */
export interface NetworkConfigurationDTO {
  /**
   *
   * @type {NetworkPropertiesDTO}
   * @memberof NetworkConfigurationDTO
   */
  network: NetworkPropertiesDTO;
  /**
   *
   * @type {ChainPropertiesDTO}
   * @memberof NetworkConfigurationDTO
   */
  chain: ChainPropertiesDTO;
  /**
   *
   * @type {PluginsPropertiesDTO}
   * @memberof NetworkConfigurationDTO
   */
  plugins: PluginsPropertiesDTO;
}
export declare function NetworkConfigurationDTOFromJSON(json: any): NetworkConfigurationDTO;
export declare function NetworkConfigurationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkConfigurationDTO;
export declare function NetworkConfigurationDTOToJSON(value?: NetworkConfigurationDTO | null): any;
