/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmbeddedAccountAddressRestrictionTransactionDTO } from "./EmbeddedAccountAddressRestrictionTransactionDTO";
import { EmbeddedAccountKeyLinkTransactionDTO } from "./EmbeddedAccountKeyLinkTransactionDTO";
import { EmbeddedAccountMetadataTransactionDTO } from "./EmbeddedAccountMetadataTransactionDTO";
import { EmbeddedAccountMosaicRestrictionTransactionDTO } from "./EmbeddedAccountMosaicRestrictionTransactionDTO";
import { EmbeddedAccountOperationRestrictionTransactionDTO } from "./EmbeddedAccountOperationRestrictionTransactionDTO";
import { EmbeddedAddressAliasTransactionDTO } from "./EmbeddedAddressAliasTransactionDTO";
import { EmbeddedHashLockTransactionDTO } from "./EmbeddedHashLockTransactionDTO";
import { EmbeddedMosaicAddressRestrictionTransactionDTO } from "./EmbeddedMosaicAddressRestrictionTransactionDTO";
import { EmbeddedMosaicAliasTransactionDTO } from "./EmbeddedMosaicAliasTransactionDTO";
import { EmbeddedMosaicDefinitionTransactionDTO } from "./EmbeddedMosaicDefinitionTransactionDTO";
import { EmbeddedMosaicGlobalRestrictionTransactionDTO } from "./EmbeddedMosaicGlobalRestrictionTransactionDTO";
import { EmbeddedMosaicMetadataTransactionDTO } from "./EmbeddedMosaicMetadataTransactionDTO";
import { EmbeddedMosaicSupplyChangeTransactionDTO } from "./EmbeddedMosaicSupplyChangeTransactionDTO";
import { EmbeddedMultisigAccountModificationTransactionDTO } from "./EmbeddedMultisigAccountModificationTransactionDTO";
import { EmbeddedNamespaceMetadataTransactionDTO } from "./EmbeddedNamespaceMetadataTransactionDTO";
import { EmbeddedNamespaceRegistrationTransactionDTO } from "./EmbeddedNamespaceRegistrationTransactionDTO";
import { EmbeddedNodeKeyLinkTransactionDTO } from "./EmbeddedNodeKeyLinkTransactionDTO";
import { EmbeddedSecretLockTransactionDTO } from "./EmbeddedSecretLockTransactionDTO";
import { EmbeddedSecretProofTransactionDTO } from "./EmbeddedSecretProofTransactionDTO";
import { EmbeddedTransactionMetaDTO } from "./EmbeddedTransactionMetaDTO";
import { EmbeddedTransferTransactionDTO } from "./EmbeddedTransferTransactionDTO";
import { EmbeddedVotingKeyLinkTransactionDTO } from "./EmbeddedVotingKeyLinkTransactionDTO";
import { EmbeddedVrfKeyLinkTransactionDTO } from "./EmbeddedVrfKeyLinkTransactionDTO";

/**
 *
 * @export
 * @interface EmbeddedTransactionInfoDTO
 */
export interface EmbeddedTransactionInfoDTO {
  /**
   * Internal resource identifier.
   * @type {string}
   * @memberof EmbeddedTransactionInfoDTO
   */
  id: string;
  /**
   *
   * @type {EmbeddedTransactionMetaDTO}
   * @memberof EmbeddedTransactionInfoDTO
   */
  meta: EmbeddedTransactionMetaDTO;
  /**
   *
   * @type {EmbeddedAccountKeyLinkTransactionDTO | EmbeddedNodeKeyLinkTransactionDTO | EmbeddedVrfKeyLinkTransactionDTO | EmbeddedVotingKeyLinkTransactionDTO | EmbeddedHashLockTransactionDTO | EmbeddedSecretLockTransactionDTO | EmbeddedSecretProofTransactionDTO | EmbeddedAccountMetadataTransactionDTO | EmbeddedMosaicMetadataTransactionDTO | EmbeddedNamespaceMetadataTransactionDTO | EmbeddedMosaicDefinitionTransactionDTO | EmbeddedMosaicSupplyChangeTransactionDTO | EmbeddedNamespaceRegistrationTransactionDTO | EmbeddedAddressAliasTransactionDTO | EmbeddedMosaicAliasTransactionDTO | EmbeddedMultisigAccountModificationTransactionDTO | EmbeddedAccountAddressRestrictionTransactionDTO | EmbeddedAccountMosaicRestrictionTransactionDTO | EmbeddedAccountOperationRestrictionTransactionDTO | EmbeddedMosaicGlobalRestrictionTransactionDTO | EmbeddedMosaicAddressRestrictionTransactionDTO | EmbeddedTransferTransactionDTO}
   * @memberof EmbeddedTransactionInfoDTO
   */
  transaction: EmbeddedAccountKeyLinkTransactionDTO | EmbeddedNodeKeyLinkTransactionDTO | EmbeddedVrfKeyLinkTransactionDTO | EmbeddedVotingKeyLinkTransactionDTO | EmbeddedHashLockTransactionDTO | EmbeddedSecretLockTransactionDTO | EmbeddedSecretProofTransactionDTO | EmbeddedAccountMetadataTransactionDTO | EmbeddedMosaicMetadataTransactionDTO | EmbeddedNamespaceMetadataTransactionDTO | EmbeddedMosaicDefinitionTransactionDTO | EmbeddedMosaicSupplyChangeTransactionDTO | EmbeddedNamespaceRegistrationTransactionDTO | EmbeddedAddressAliasTransactionDTO | EmbeddedMosaicAliasTransactionDTO | EmbeddedMultisigAccountModificationTransactionDTO | EmbeddedAccountAddressRestrictionTransactionDTO | EmbeddedAccountMosaicRestrictionTransactionDTO | EmbeddedAccountOperationRestrictionTransactionDTO | EmbeddedMosaicGlobalRestrictionTransactionDTO | EmbeddedMosaicAddressRestrictionTransactionDTO | EmbeddedTransferTransactionDTO;
}
export declare function EmbeddedTransactionInfoDTOFromJSON(json: any): EmbeddedTransactionInfoDTO;
export declare function EmbeddedTransactionInfoDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddedTransactionInfoDTO;
export declare function EmbeddedTransactionInfoDTOToJSON(value?: EmbeddedTransactionInfoDTO | null): any;
