/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NodeStatusEnum } from './NodeStatusEnum';
/**
 *
 * @export
 * @interface NodeHealthDTO
 */
export interface NodeHealthDTO {
  /**
   *
   * @type {NodeStatusEnum}
   * @memberof NodeHealthDTO
   */
  apiNode: NodeStatusEnum;
  /**
   *
   * @type {NodeStatusEnum}
   * @memberof NodeHealthDTO
   */
  db: NodeStatusEnum;
}
export declare function NodeHealthDTOFromJSON(json: any): NodeHealthDTO;
export declare function NodeHealthDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeHealthDTO;
export declare function NodeHealthDTOToJSON(value?: NodeHealthDTO | null): any;
