/**
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountAddressRestrictionTransactionDTO, } from './AccountAddressRestrictionTransactionDTO';
import { AccountKeyLinkTransactionDTO } from "./AccountKeyLinkTransactionDTO";
import { AccountMetadataTransactionDTO } from "./AccountMetadataTransactionDTO";
import { AccountMosaicRestrictionTransactionDTO } from "./AccountMosaicRestrictionTransactionDTO";
import { AccountOperationRestrictionTransactionDTO } from "./AccountOperationRestrictionTransactionDTO";
import { AddressAliasTransactionDTO } from "./AddressAliasTransactionDTO";
import { AggregateTransactionDTO } from "./AggregateTransactionDTO";
import { AggregateTransactionExtendedDTO } from "./AggregateTransactionExtendedDTO";
import { EmbeddedAccountAddressRestrictionTransactionDTO } from "./EmbeddedAccountAddressRestrictionTransactionDTO";
import { EmbeddedAccountKeyLinkTransactionDTO } from "./EmbeddedAccountKeyLinkTransactionDTO";
import { EmbeddedAccountMetadataTransactionDTO } from "./EmbeddedAccountMetadataTransactionDTO";
import { EmbeddedAccountMosaicRestrictionTransactionDTO } from "./EmbeddedAccountMosaicRestrictionTransactionDTO";
import { EmbeddedAccountOperationRestrictionTransactionDTO } from "./EmbeddedAccountOperationRestrictionTransactionDTO";
import { EmbeddedAddressAliasTransactionDTO } from "./EmbeddedAddressAliasTransactionDTO";
import { EmbeddedHashLockTransactionDTO } from "./EmbeddedHashLockTransactionDTO";
import { EmbeddedMosaicAddressRestrictionTransactionDTO } from "./EmbeddedMosaicAddressRestrictionTransactionDTO";
import { EmbeddedMosaicAliasTransactionDTO } from "./EmbeddedMosaicAliasTransactionDTO";
import { EmbeddedMosaicDefinitionTransactionDTO } from "./EmbeddedMosaicDefinitionTransactionDTO";
import { EmbeddedMosaicGlobalRestrictionTransactionDTO } from "./EmbeddedMosaicGlobalRestrictionTransactionDTO";
import { EmbeddedMosaicMetadataTransactionDTO } from "./EmbeddedMosaicMetadataTransactionDTO";
import { EmbeddedMosaicSupplyChangeTransactionDTO } from "./EmbeddedMosaicSupplyChangeTransactionDTO";
import { EmbeddedMultisigAccountModificationTransactionDTO } from "./EmbeddedMultisigAccountModificationTransactionDTO";
import { EmbeddedNamespaceMetadataTransactionDTO } from "./EmbeddedNamespaceMetadataTransactionDTO";
import { EmbeddedNamespaceRegistrationTransactionDTO } from "./EmbeddedNamespaceRegistrationTransactionDTO";
import { EmbeddedNodeKeyLinkTransactionDTO } from "./EmbeddedNodeKeyLinkTransactionDTO";
import { EmbeddedSecretLockTransactionDTO } from "./EmbeddedSecretLockTransactionDTO";
import { EmbeddedSecretProofTransactionDTO } from "./EmbeddedSecretProofTransactionDTO";
import { EmbeddedTransactionMetaDTO } from "./EmbeddedTransactionMetaDTO";
import { EmbeddedTransferTransactionDTO } from "./EmbeddedTransferTransactionDTO";
import { EmbeddedVotingKeyLinkTransactionDTO } from "./EmbeddedVotingKeyLinkTransactionDTO";
import { EmbeddedVrfKeyLinkTransactionDTO } from "./EmbeddedVrfKeyLinkTransactionDTO";
import { HashLockTransactionDTO } from "./HashLockTransactionDTO";
import { MosaicAddressRestrictionTransactionDTO } from "./MosaicAddressRestrictionTransactionDTO";
import { MosaicAliasTransactionDTO } from "./MosaicAliasTransactionDTO";
import { MosaicDefinitionTransactionDTO } from "./MosaicDefinitionTransactionDTO";
import { MosaicGlobalRestrictionTransactionDTO } from "./MosaicGlobalRestrictionTransactionDTO";
import { MosaicMetadataTransactionDTO } from "./MosaicMetadataTransactionDTO";
import { MosaicSupplyChangeTransactionDTO } from "./MosaicSupplyChangeTransactionDTO";
import { MultisigAccountModificationTransactionDTO } from "./MultisigAccountModificationTransactionDTO";
import { NamespaceMetadataTransactionDTO } from "./NamespaceMetadataTransactionDTO";
import { NamespaceRegistrationTransactionDTO } from "./NamespaceRegistrationTransactionDTO";
import { NodeKeyLinkTransactionDTO } from "./NodeKeyLinkTransactionDTO";
import { SecretLockTransactionDTO } from "./SecretLockTransactionDTO";
import { SecretProofTransactionDTO } from "./SecretProofTransactionDTO";
import { TransactionMetaDTO } from "./TransactionMetaDTO";
import { TransferTransactionDTO } from "./TransferTransactionDTO";
import { VotingKeyLinkTransactionDTO } from "./VotingKeyLinkTransactionDTO";
import { VrfKeyLinkTransactionDTO } from "./VrfKeyLinkTransactionDTO";

/**
 *
 * @export
 * @interface TransactionInfoDTO
 */
export interface TransactionInfoDTO {
  /**
   * Internal resource identifier.
   * @type {string}
   * @memberof TransactionInfoDTO
   */
  id: string;
  /**
   *
   * @type {TransactionMetaDTO | EmbeddedTransactionMetaDTO}
   * @memberof TransactionInfoDTO
   */
  meta: TransactionMetaDTO | EmbeddedTransactionMetaDTO;
  /**
   *
   * @type {AccountKeyLinkTransactionDTO | EmbeddedAccountKeyLinkTransactionDTO | NodeKeyLinkTransactionDTO | EmbeddedNodeKeyLinkTransactionDTO | VrfKeyLinkTransactionDTO | EmbeddedVrfKeyLinkTransactionDTO | VotingKeyLinkTransactionDTO | EmbeddedVotingKeyLinkTransactionDTO | AggregateTransactionDTO | AggregateTransactionExtendedDTO | HashLockTransactionDTO | EmbeddedHashLockTransactionDTO | SecretLockTransactionDTO | EmbeddedSecretLockTransactionDTO | SecretProofTransactionDTO | EmbeddedSecretProofTransactionDTO | AccountMetadataTransactionDTO | EmbeddedAccountMetadataTransactionDTO | MosaicMetadataTransactionDTO | EmbeddedMosaicMetadataTransactionDTO | NamespaceMetadataTransactionDTO | EmbeddedNamespaceMetadataTransactionDTO | MosaicDefinitionTransactionDTO | EmbeddedMosaicDefinitionTransactionDTO | MosaicSupplyChangeTransactionDTO | EmbeddedMosaicSupplyChangeTransactionDTO | NamespaceRegistrationTransactionDTO | EmbeddedNamespaceRegistrationTransactionDTO | AddressAliasTransactionDTO | EmbeddedAddressAliasTransactionDTO | MosaicAliasTransactionDTO | EmbeddedMosaicAliasTransactionDTO | MultisigAccountModificationTransactionDTO | EmbeddedMultisigAccountModificationTransactionDTO | AccountAddressRestrictionTransactionDTO | EmbeddedAccountAddressRestrictionTransactionDTO | AccountMosaicRestrictionTransactionDTO | EmbeddedAccountMosaicRestrictionTransactionDTO | AccountOperationRestrictionTransactionDTO | EmbeddedAccountOperationRestrictionTransactionDTO | MosaicGlobalRestrictionTransactionDTO | EmbeddedMosaicGlobalRestrictionTransactionDTO | MosaicAddressRestrictionTransactionDTO | EmbeddedMosaicAddressRestrictionTransactionDTO | TransferTransactionDTO | EmbeddedTransferTransactionDTO}
   * @memberof TransactionInfoDTO
   */
  transaction: AccountKeyLinkTransactionDTO | EmbeddedAccountKeyLinkTransactionDTO | NodeKeyLinkTransactionDTO | EmbeddedNodeKeyLinkTransactionDTO | VrfKeyLinkTransactionDTO | EmbeddedVrfKeyLinkTransactionDTO | VotingKeyLinkTransactionDTO | EmbeddedVotingKeyLinkTransactionDTO | AggregateTransactionDTO | AggregateTransactionExtendedDTO | HashLockTransactionDTO | EmbeddedHashLockTransactionDTO | SecretLockTransactionDTO | EmbeddedSecretLockTransactionDTO | SecretProofTransactionDTO | EmbeddedSecretProofTransactionDTO | AccountMetadataTransactionDTO | EmbeddedAccountMetadataTransactionDTO | MosaicMetadataTransactionDTO | EmbeddedMosaicMetadataTransactionDTO | NamespaceMetadataTransactionDTO | EmbeddedNamespaceMetadataTransactionDTO | MosaicDefinitionTransactionDTO | EmbeddedMosaicDefinitionTransactionDTO | MosaicSupplyChangeTransactionDTO | EmbeddedMosaicSupplyChangeTransactionDTO | NamespaceRegistrationTransactionDTO | EmbeddedNamespaceRegistrationTransactionDTO | AddressAliasTransactionDTO | EmbeddedAddressAliasTransactionDTO | MosaicAliasTransactionDTO | EmbeddedMosaicAliasTransactionDTO | MultisigAccountModificationTransactionDTO | EmbeddedMultisigAccountModificationTransactionDTO | AccountAddressRestrictionTransactionDTO | EmbeddedAccountAddressRestrictionTransactionDTO | AccountMosaicRestrictionTransactionDTO | EmbeddedAccountMosaicRestrictionTransactionDTO | AccountOperationRestrictionTransactionDTO | EmbeddedAccountOperationRestrictionTransactionDTO | MosaicGlobalRestrictionTransactionDTO | EmbeddedMosaicGlobalRestrictionTransactionDTO | MosaicAddressRestrictionTransactionDTO | EmbeddedMosaicAddressRestrictionTransactionDTO | TransferTransactionDTO | EmbeddedTransferTransactionDTO;
}
export declare function TransactionInfoDTOFromJSON(json: any): TransactionInfoDTO;
export declare function TransactionInfoDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionInfoDTO;
export declare function TransactionInfoDTOToJSON(value?: TransactionInfoDTO | null): any;
